const catalogData = [
        {
          link: "https://drive.google.com/file/d/1SF69Nu2CnPMzCuaLOsTyYXcKmOzLVlIJ/view?usp=drive_link",
          imageSrc: "frontpage/merino100.png",
          altText: "Merino 100 Catalogue Cover",
          category: "1mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1SLycgo99NxPWdp3xUlzpgusP2S6zTkd3/view?usp=drive_link",
          imageSrc: "frontpage/merino800.png",
          altText: "Merino 800 Catalogue Cover",
          category: "0.92mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1H3JU93y_gvDCG2W_bmGjgyjIJZVLkm4r/view?usp=drive_link",
          imageSrc: "frontpage/greenlam 100.png",
          altText: "Greenlam 100 Catalogue Cover",
          category: "1mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1NdyISZ69qEPS6yg1a0GsIyHN1DXwe2mC/view?usp=drive_link",
          imageSrc: "frontpage/royal touch.png",
          altText: "Royal Touch Catalogue Cover",
          category: "1mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/155lodOK-MyfoRLqiVlJHNvB_8_NXJEe6/view?usp=drive_link",
          imageSrc: "frontpage/sunmica 800.png",
          altText: "Sunmica 800 Catalogue Cover",
          category: "0.92mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1AcxUi7Da4tnshqL5l7m7bVAr7IwTwmhh/view?usp=drive_link",
          imageSrc: "frontpage/sunmica 100.png",
          altText: "Sunmica 100 Catalogue Cover",
          category: "1mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1SiAC6-rYF88kdAY07DnGuucwuF3y403w/view?usp=drive_link",
          imageSrc: "frontpage/finemica.png",
          altText: "Finemica Catalogue Cover",
          category: "0.92 Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1Sku8sYYLgCm4eznlK2G6DIdpageghPZ5/view?usp=drive_link",
          imageSrc: "frontpage/ipl.png",
          altText: "IPL Catalogue Cover",
          category: "0.92 Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1reSSq9_yForblbiUsoGhAv4gfAJ2plcz/view?usp=drive_link",
          imageSrc: "frontpage/sainik.png",
          altText: "Sainik Catalogue Cover",
          category: "1mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1SdqZ4i4c9Ziey32PoUeZHhi2mhRTvO1u/view?usp=drive_link",
          imageSrc: "frontpage/virgo 100.png",
          altText: "Virgo 100 Catalogue Cover",
          category: "1mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1T3YD_sO5kMTnHg8UUDDI_5qhZVS6MzJe/view?usp=drive_link",
          imageSrc: "frontpage/virgo800.png",
          altText: "Virgo 800 Catalogue Cover",
          category: "0.92mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1A8_mkaDteQFWFIrqWUG1mBXaJpe_-PEM/view?usp=drive_link",
          imageSrc: "frontpage/tocca.png",
          altText: "Tocca Catalogue Cover",
          category: "1mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1gkQzhaJE-FRlwgdUKhcNDbYFPJRtPD_b/view?usp=drive_link",
          imageSrc: "frontpage/neltouch.png",
          altText: "Neltouch Catalogue Cover",
          category: "1mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1SxKcs2bWFHRizj1nJ1RLpezZ8-NagGSS/view?usp=drive_link",
          imageSrc: "frontpage/bonanzlam.png",
          altText: "Bonanzlam Catalogue Cover",
          category: "0.92 Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1TNy8OmiptDNij3kZFOkK_anG_e_LUfS8/view?usp=drive_link",
          imageSrc: "frontpage/greentouch.png",
          altText: "Green Touch Catalogue Cover",
          category: "0.92mm Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1TNqGJzowHztSQXB6ANcFGvRmG0700wjn/view?usp=drive_link",
          imageSrc: "frontpage/realtouch.png",
          altText: "Real Touch Catalogue Cover",
          category: "1mm Laminate",
        },
         {
          link: "https://drive.google.com/file/d/1TNqGJzowHztSQXB6ANcFGvRmG0700wjn/view?usp=drive_link",
          imageSrc: "frontpage/enzo.png",
          altText: "Enzo Catalogue Cover",
          category: "Acrylic Laminate",
        },
        {
          link: "https://drive.google.com/file/d/1TNqGJzowHztSQXB6ANcFGvRmG0700wjn/view?usp=drive_link",
          imageSrc: "frontpage/akwood.png",
          altText: "AK Wood Catalogue Cover",
          category: "Fabric Laminate",
        },
      ];